### ISSUE TITLE
I don't see CAS Protocol in Admin Console

### ISSUE THREAD

**Issue by langtucodoc** [jacekkow/keycloak-protocol-cas#116]
Hello,

I have already installed keycloak-protocol-cas, but i didn't see it in Admin Consle

![image](https://github.com/user-attachments/assets/da8d733b-fbc2-4e31-91b2-9a17fba4a703)

**Comment by jacekkow** [comment]
It is not a identity provider - this extension is for clients only (go to client and there you can add a client that utilizes "cas" protocol).
