### ISSUE TITLE
Question: Can the CAS protocol/extension be used for authorization ? 

### ISSUE THREAD

**Issue by RaveNN-0** [jacekkow/keycloak-protocol-cas#126]
Hello. I was testing Keycloak and saw that it can handle authorization in the OpenID protocol.

Since an objective of my instituition is centralizing authorization handling, is it possible do to this with the CAS protocol/extension or would we have to switch the services to use OpenID protocol ?

Thank you !

**Comment by jacekkow** [comment]
CAS is an authentication-only protocol. You could, theoretically, do allow/deny per-service but nothing more than that. If you need roles and more granular control - go with OpenID. CAS protocol is a relic, but still used.
