### ISSUE TITLE
Backchannel logout not working due to invalid client session note set

### ISSUE THREAD

**Issue by malinowskij** [jacekkow/keycloak-protocol-cas#129]
After many tests I am unable to trigger backchannel logout.

I have debugged the plugin code and have come to the following conclusions:
1. In the CASLoginProtocol class, the tickeet is retrieved from the client session notes
2. However, during validateService the ticket is set with the ticket prefix key, i.e. "ST-", instead of "service_ticket" (AbstractValidateEndpoint:154)

![obraz](https://github.com/user-attachments/assets/e9acd664-cf6e-457e-9e85-4ab2abc69e7e)

Looking at the commit history, you can see the change:
![obraz](https://github.com/user-attachments/assets/1d02b50f-9af7-43a9-bbeb-b1b293a4917f)

This causes serviceTicket to always be null.

**Comment by Stelmach83** [comment]
@jacekkow please take a loot at this
