### ISSUE TITLE
gateway=true option causes error page to be shown

### ISSUE THREAD

**Issue by Mystikal57** [jacekkow/keycloak-protocol-cas#17]
Hello,

When i click on cas button on my app (moodle), i'm redirected to keycloak and i have this message:
we are sorry... an error occured
I click on back button, and reclick on cas button -> all is well.. 

If i close the browser and retry, same thing.

I have this message in log:
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-37) Uncaught server error: org.jboss.resteasy.core.NoMessageBodyWriterFoundFailure: Could not find MessageBodyWriter for response object of type: org.keycloak.protocol.LoginProtocol$Error of media type: text/html;charset=UTF-8

Do you have an idea ?

Thank you

**Comment by Mystikal57** [comment]
moodle add "&gateway=true" in the url....

**Comment by jacekkow** [comment]
"gateway=true" is a valid option and should be handled correctly - I'll take a look at this.

**Comment by jacekkow** [comment]
Could you recheck Moodle behavior (with gateway option) using this version of the module?
[package-dev-1.zip](https://github.com/jacekkow/keycloak-protocol-cas/files/5395410/package-dev-1.zip)

**Comment by Mystikal57** [comment]
Hello, 
I will test monday at work
Thank you

**Comment by Mystikal57** [comment]
Hello, it's working ! thank you very much !

**Comment by jacekkow** [comment]
Sorry for writing after a year, but for the record - here's the commit with fix:
https://github.com/jacekkow/keycloak-protocol-cas/commit/3882f0eb56e0b699c071f77bb914b6739b163deb
