### ISSUE TITLE
Did not logout when session idle timeout

### ISSUE THREAD

**Issue by zqzq71** [jacekkow/keycloak-protocol-cas#20]
Hi guys, 

I have a system with keycloak, one backend and one frontend. Using this plugin between keycloak and backend. Using vue-keycloak-js between keycloak and frontend. Single Sign On and Single Logout works well. When logout event happened, backend recevie the logout message, fontend and backend logout together. 

But I found. When the keycloak session idle timeout, the sessions have been destroyed (checked by keycloak session panel), frontend have been logout, backend still logged in and did not recevie logout message.  

If I login again in frontend with different accout, the frontend will be using current user, and backend will still using before user. is there any methods to solve this problem ?

**Comment by jacekkow** [comment]
If you are using vue-keycloak-js, then this plugin for CAS protocol (keycloak-protocol-cas) is definitely not used - please report any issues/problems to Keycloak, not me.

Nevertheless "frontend" and "backend" sessions (including any timeouts) are completely different entities - do not expect synchronization between the two, unless you specifically designed it. This is how Keycloak should operate being an SSO service.
