### ISSUE TITLE
Page Not Found Error With CAS Endpoint

### ISSUE THREAD

**Issue by matthew-williamson-sd** [jacekkow/keycloak-protocol-cas#27]
Hi,

I'm having some issues running keycloak-protocol-cas with keycloak 12.0.4. I add the jar to the deployments directory. I can see CAS as an option in the frontend and tomcat says it's been laoded so seems to be working. My application seems to redirect to the correct url (i.e. http://localhost:8180/auth/realms/master/protocol/cas) but gets a 'Page Not Found'

I've tested the app against Apereo's test server and it appears to work, so unsure what the issue could be.

Any help you can give would be appreciated, and I apologise if I'm missing something blindingly obvious!

![Screenshot 2021-05-10 at 17 46 44](https://user-images.githubusercontent.com/52041936/117694994-b17fb400-b1b7-11eb-9893-d21d3b8fd6cc.png)

![Screenshot 2021-05-10 at 17 48 59](https://user-images.githubusercontent.com/52041936/117696211-f3f5c080-b1b8-11eb-8a1f-90960b78d892.png)

**Comment by jacekkow** [comment]
`http://localhost:8180/auth/realms/master/protocol/cas` is not a correct URL! Per [CAS protocol specification](https://apereo.github.io/cas/6.3.x/protocol/CAS-Protocol-V2-Specification.html#21-login-as-credential-requestor) you must append `/login` to the URL to get the authentication endpoint.

Hence the correct URL would be `http://localhost:8180/auth/realms/master/protocol/cas/login` (plus necessary parameters like `service`)
