### ISSUE TITLE
keycloak  error  We are sorry... Client not found.

### ISSUE THREAD

**Issue by banghansun** [jacekkow/keycloak-protocol-cas#34]
I want to use "keycloak-protocol-cas" to do single sign-on for "JumpServer", but I'm having the following problem
I followed the official jumpServer documentation：
https://jumpserver.readthedocs.io/zh/master/admin-guide/authentication/cas/

![image](https://user-images.githubusercontent.com/34332009/130170512-e6dd124d-4748-4368-a13e-cac53c8b81c2.png)
keycloak  error  We are sorry... Client not found.

Below is my setup details

keycloak：
![image](https://user-images.githubusercontent.com/34332009/130170890-7a0db8ef-2e8d-4055-896c-0b4570098cda.png)

server:

![image](https://user-images.githubusercontent.com/34332009/130170919-fab89440-30f6-40f3-9450-f8c02c86b773.png)

**Comment by banghansun** [comment]
keycloak version : 14.00
keycloak-protocol-cas version 14.00

**Comment by jacekkow** [comment]
Since "service" parameter in your request starts with "http://172.16.30.188:80/" you must either add version with ":80" to "Valid Redirect URIs" or drop ":80" from CAS_ROOT_PROXIED_AS parameter in server configuration.

**Comment by banghansun** [comment]
After the configuration according to the method you give，
The KeyCloak login screen is displayed
![image](https://user-images.githubusercontent.com/34332009/130410007-94790b75-44e4-4b6f-948d-30da478a2266.png)

But when you click the login button, an error occurs ---403 Forbidden

![image](https://user-images.githubusercontent.com/34332009/130409836-0dec7223-0d68-4acc-862a-bb851d09316b.png)

Thanks for your help~~~ C:

**Comment by banghansun** [comment]
I have solved the above problems. Thanks for your help!
