### ISSUE TITLE
Unable to connect to CAS Server URL - error 404

### ISSUE THREAD

**Issue by DesertRider** [jacekkow/keycloak-protocol-cas#36]
Hi,

I'm trying to authenticate an application that currently use a CAS server with Keycloak with keycloak-protocol-cas extension. I'm using the latest version (15.0.2) but also tried with another server (12.0.1) with same result. Both have the corresponding version of the extension correctly deployed.

I've created the client and chose "cas" as the client protocol, with the Valid Redirect URI as "https://accesdistant.xxx/p/*". The Installation - Plain CAS Configuration shows this:
```
CAS Server URL: https://sso.xxx/auth/realms/yyy/protocol/cas
CAS Protocol: CAS 2.0/3.0 (SAML 1.1 is not supported)
Use CAS REST API: false (unsupported)

```

First point here: the documentation states that _Enter https://your.keycloak.host/auth/realms/master/protocol/cas as the CAS URL into your SP._ 
Either I misunderstand this point, but I think the URL should **not** be with realm master, but rather the realm where you have your client created... can you confirm?

I configured my Apache server to redirect the login page to https://sso.xxx/auth/realms/yyy/protocol/cas:

```
  CASLoginURL https://accesdistant.xxx/authdist/

    ProxyPass /authdist/ https://sso.xxx/auth/realms/yyy/protocol/cas
    <Location /authdist/>
        ProxyPassReverse https://sso.xxx/auth/realms/yyy/protocol/cas
    </Location>

```

Either way I try this I always have a 404 calling Keycloak with the CAS extension... even a simple curl yield the same result.

`curl -k https://sso.xxx/auth/realms/yyy/protocol/cas?service=https%3a%2f%2faccesdistant.xxx%2fp%2f
{"error":"RESTEASY003210: Could not find resource for full path: https://sso.xxx/auth/realms/yyy/protocol/cas?service=https%3a%2f%2faccesdistant.xxx%2fp%2f"}
`

Can you point me where I'm wrong?

**Comment by DesertRider** [comment]
Reading issue #27 (https://github.com/jacekkow/keycloak-protocol-cas/issues/27) I found some answers...

As this issue is a duplicate one, you can delete it.

**Comment by jacekkow** [comment]
@PaulGitProject - ask questions in a separate ticket, not here.
