### ISSUE TITLE
about springboot use cas-client

### ISSUE THREAD

**Issue by gaozhenyusky** [jacekkow/keycloak-protocol-cas#40]
hi, i use cas-client-autoconfig-support in my springboot project, and the url parm is like this 
`service=http%3A%2F%2Flocalhost%3A8101%2F`

As you can see, the keycloak show client was not found

but if i use no urlencoded url, the keycloak work ok

I beg your help

**Comment by jacekkow** [comment]
See
https://github.com/jacekkow/keycloak-protocol-cas/issues/34#issue-975208047
and
https://github.com/jacekkow/keycloak-protocol-cas/issues/34#issuecomment-902519927

You must configure your client to include `http://localhost:8101/` in "Valid Redirect URIs".

**Comment by jacekkow** [comment]
Feel free to ask further questions.

**Comment by gaozhenyusky** [comment]
thx for ur help!  The jump was successful!
