### ISSUE TITLE
Support of Keycloak 17.0.0

### ISSUE THREAD

**Issue by Olivier-SP** [jacekkow/keycloak-protocol-cas#44]
Do you have any plan to update this plugin to support Keycloak 17.0.0 ?

Thanks !

**Comment by jacekkow** [comment]
Theoretically I should have an automatic pull request created for each new Keycloak version.

Unfortunately, there is some problem with Maven Central and maven-metadata.xml have not been updated for Keycloak 17.0.0 release - the latest version listed is 16.1.1:
https://repo1.maven.org/maven2/org/keycloak/keycloak-core/maven-metadata.xml

I have raised https://issues.sonatype.org/browse/MVNCENTRAL-7281 for that.

Meanwhile I'll prepare the pull request manually. You can also try using version 16.1.1 with Keycloak 17.0.0 - it is quite probable that it will work flawlessly out-of-the-box.

**Comment by jacekkow** [comment]
I see that with Keycloak 17 Wildfly is no longer used as an application server. I would need to update all the tooling and documentation to reflect that.

It would be great if you could check whether plugin 16.1.1 works with Keycloak 17.0.0.

**Comment by Olivier-SP** [comment]
> I see that with Keycloak 17 Wildfly is no longer used as an application server. I would need to update all the tooling and documentation to reflect that.
> 
> It would be great if you could check whether plugin 16.1.1 works with Keycloak 17.0.0.

Thanks for your reply !
True, Keycloak 17 moved to Quarkus.

We're going to test the plugin asap and let you know the results !

**Comment by jacekkow** [comment]
As far as I can tell version 16.1.1 works fine with Quarkus distribution of Keycloak 17.0.0.

You can track progress of tooling updates here: https://github.com/jacekkow/keycloak-protocol-cas/pull/45

**Comment by jacekkow** [comment]
PR #45 has been merged.
